import type { Category, Fulfillment, Kind } from "./types";

export type SeedListing = {
  id: string;
  kind: Kind;
  category: Category;
  title: string;
  description: string;
  city: string;
  region: string;
  lat: number;
  lng: number;
  fulfillment: Fulfillment;
  nationalOk: boolean;
  condition: string | null;
  giverName: string;
  estimatedLbs: number;
  hoursAgo: number;
  pickupPlace?: string | null;
};

export const SEED_PHOTOS: Record<string, string> = {
  "oak-dresser-alamosa": "/listings/oak-dresser-alamosa.jpg",
  "zucchini-flood": "/listings/zucchini-flood.jpg",
  "loaf-by-six": "/listings/loaf-by-six.jpg",
  "kids-coats-5t": "/listings/kids-coats-5t.jpg",
  "tomato-starts": "/listings/tomato-starts.jpg",
  "camping-stove-lend": "/listings/camping-stove-lend.jpg",
  "used-crib-alamosa": "/listings/used-crib-alamosa.jpg",
  "campus-bike-give": "/listings/campus-bike-give.jpg",
  "desk-logan-give": "/listings/desk-logan-give.jpg",
};

export const SEED_USER = "manna-seed";

export const SEED_LISTINGS: SeedListing[] = [
  {
    id: "oak-dresser-alamosa",
    kind: "give",
    category: "goods",
    title: "Solid oak dresser, five drawers",
    description:
      "Heavy, honest furniture from a house we are emptying. One drawer stickers a little. You will need two people or a truck. On the porch on State Ave through Thursday.",
    city: "Alamosa",
    region: "CO",
    lat: 37.4695,
    lng: -105.87,
    fulfillment: "porch",
    nationalOk: false,
    condition: "Good",
    giverName: "Elena",
    estimatedLbs: 80,
    hoursAgo: 3,
    pickupPlace: "Porch on State Ave",
  },
  {
    id: "zucchini-flood",
    kind: "give",
    category: "food",
    title: "Garden zucchini — please take some",
    description:
      "The vines did what vines do. Eight to ten firm squash, no pesticides. Bag them on the shaded side of the house by 7 tonight.",
    city: "Alamosa",
    region: "CO",
    lat: 37.4712,
    lng: -105.865,
    fulfillment: "porch",
    nationalOk: false,
    condition: null,
    giverName: "Tomás",
    estimatedLbs: 12,
    hoursAgo: 1,
    pickupPlace: "Shaded side of the house",
  },
  {
    id: "truck-saturday",
    kind: "offer",
    category: "help",
    title: "Pickup truck, Saturday morning",
    description:
      "I have a F-150 free from 8 to noon. Happy to help move a couch, haul brush, or take a load to the dump. Stay in the valley. Coffee on me after.",
    city: "Alamosa",
    region: "CO",
    lat: 37.468,
    lng: -105.872,
    fulfillment: "pickup",
    nationalOk: false,
    condition: null,
    giverName: "Marcus",
    estimatedLbs: 0,
    hoursAgo: 6,
  },
  {
    id: "need-a-crib",
    kind: "ask",
    category: "kids",
    title: "Looking for a crib",
    description:
      "Baby due in November. We do not need new — a sturdy used crib that meets current safety standards would be a gift. Can pick up anywhere in the valley.",
    city: "Alamosa",
    region: "CO",
    lat: 37.47,
    lng: -105.868,
    fulfillment: "pickup",
    nationalOk: false,
    condition: null,
    giverName: "Sofia",
    estimatedLbs: 0,
    hoursAgo: 20,
  },
  {
    id: "camping-stove-lend",
    kind: "lend",
    category: "goods",
    title: "Two-burner camp stove, this weekend",
    description:
      "Coleman stove, works. Back by Monday evening and we are even. I used to buy a new one every trip. This is better.",
    city: "Alamosa",
    region: "CO",
    lat: 37.466,
    lng: -105.874,
    fulfillment: "public",
    nationalOk: false,
    condition: "Good",
    giverName: "Priya",
    estimatedLbs: 8,
    hoursAgo: 8,
    pickupPlace: "Alamosa public library lot",
  },
  {
    id: "kids-coats-5t",
    kind: "give",
    category: "kids",
    title: "Kids winter coats, size 5T",
    description:
      "Two coats, one navy, one red, both from last season and still thick. Outgrown in a blink. Cleaned. Porch bin labeled Manna.",
    city: "Alamosa",
    region: "CO",
    lat: 37.473,
    lng: -105.861,
    fulfillment: "porch",
    nationalOk: false,
    condition: "Very good",
    giverName: "Hannah",
    estimatedLbs: 4,
    hoursAgo: 12,
    pickupPlace: "Porch bin labeled Manna",
  },
  {
    id: "fence-2x4s",
    kind: "give",
    category: "materials",
    title: "Leftover fence boards and 2x4s",
    description:
      "About twenty eight-foot boards, some cut-offs, a coffee can of galvanized nails. Dry, stacked under the carport. Take what you can use.",
    city: "Monte Vista",
    region: "CO",
    lat: 37.5792,
    lng: -106.1481,
    fulfillment: "pickup",
    nationalOk: false,
    condition: "Fair",
    giverName: "Dale",
    estimatedLbs: 90,
    hoursAgo: 18,
  },
  {
    id: "spanish-english",
    kind: "offer",
    category: "help",
    title: "Spanish / English — a patient hour",
    description:
      "I will sit with you over forms, a parent-teacher note, or a resume. In person in Alamosa or a video call if you are farther. No charge, no sermon.",
    city: "Alamosa",
    region: "CO",
    lat: 37.4695,
    lng: -105.87,
    fulfillment: "remote",
    nationalOk: true,
    condition: null,
    giverName: "Luz",
    estimatedLbs: 0,
    hoursAgo: 4,
  },
  {
    id: "tomato-starts",
    kind: "give",
    category: "plants",
    title: "Hardy tomato starts",
    description:
      "Amish paste and a few cherries, started in the mudroom. Six plants left. Best in the ground this week. Bring a box.",
    city: "Alamosa",
    region: "CO",
    lat: 37.475,
    lng: -105.877,
    fulfillment: "porch",
    nationalOk: false,
    condition: null,
    giverName: "Ruth",
    estimatedLbs: 6,
    hoursAgo: 2,
    pickupPlace: "Mudroom step, box ready",
  },
  {
    id: "campus-bike-ask",
    kind: "ask",
    category: "goods",
    title: "Need a bike to get to campus",
    description:
      "Adams State student. Something that stops and rolls is enough. I can fix a chain. Will pick up in town after class.",
    city: "Alamosa",
    region: "CO",
    lat: 37.469,
    lng: -105.88,
    fulfillment: "pickup",
    nationalOk: false,
    condition: null,
    giverName: "Jordan",
    estimatedLbs: 0,
    hoursAgo: 30,
  },
  {
    id: "move-out-lamp-fridge",
    kind: "give",
    category: "goods",
    title: "Mini fridge and desk lamp — campus move-out",
    description:
      "Leaving the dorm Friday. Fridge works, lamp is a cheap clamp light. First person with a car can take both. Text through Manna, not my number.",
    city: "Alamosa",
    region: "CO",
    lat: 37.4735,
    lng: -105.879,
    fulfillment: "pickup",
    nationalOk: false,
    condition: "Fair",
    giverName: "Ava",
    estimatedLbs: 45,
    hoursAgo: 9,
  },
  {
    id: "loaf-by-six",
    kind: "give",
    category: "food",
    title: "Two loaves, still warm around four",
    description:
      "I baked too much again. Country white, no dairy. Wrap them from the bench on the porch. Gone by six or they go to the birds.",
    city: "Alamosa",
    region: "CO",
    lat: 37.4672,
    lng: -105.869,
    fulfillment: "porch",
    nationalOk: false,
    condition: null,
    giverName: "June",
    estimatedLbs: 3,
    hoursAgo: 0,
    pickupPlace: "Bench on the porch",
  },
  {
    id: "community-play-tickets",
    kind: "give",
    category: "goods",
    title: "Two extra seats at the community play",
    description:
      "Saturday 7pm, Richardson Theatre. We cannot use the pair. Meet me in the lobby. They are yours.",
    city: "Alamosa",
    region: "CO",
    lat: 37.4695,
    lng: -105.87,
    fulfillment: "public",
    nationalOk: false,
    condition: null,
    giverName: "Ben",
    estimatedLbs: 0,
    hoursAgo: 14,
    pickupPlace: "Richardson Theatre lobby",
  },
  {
    id: "snow-shovel-lend",
    kind: "lend",
    category: "goods",
    title: "Snow shovel — until the melt",
    description:
      "We have two. Borrow one through the next storm and lean it back on the fence when you are done.",
    city: "Alamosa",
    region: "CO",
    lat: 37.472,
    lng: -105.866,
    fulfillment: "porch",
    nationalOk: false,
    condition: "Good",
    giverName: "Chris",
    estimatedLbs: 5,
    hoursAgo: 40,
    pickupPlace: "Lean it back on the fence",
  },
  {
    id: "resume-review-remote",
    kind: "offer",
    category: "help",
    title: "I will read your resume, once, carefully",
    description:
      "Fifteen years hiring for small shops. Send a PDF, I send notes. Remote, anywhere in the US. I will not sell you a course.",
    city: "Alamosa",
    region: "CO",
    lat: 37.4695,
    lng: -105.87,
    fulfillment: "remote",
    nationalOk: true,
    condition: null,
    giverName: "Gwen",
    estimatedLbs: 0,
    hoursAgo: 22,
  },
  {
    id: "monte-vista-chicken",
    kind: "give",
    category: "food",
    title: "Extra dozen eggs",
    description:
      "Hens are generous this week. Unwashed, from yesterday. Cooler on the step, Monte Vista. Leave the carton if you have one to swap.",
    city: "Monte Vista",
    region: "CO",
    lat: 37.5792,
    lng: -106.1481,
    fulfillment: "porch",
    nationalOk: false,
    condition: null,
    giverName: "Pat",
    estimatedLbs: 2,
    hoursAgo: 5,
    pickupPlace: "Cooler on the step",
  },
  {
    id: "del-norte-tools",
    kind: "lend",
    category: "goods",
    title: "Tile saw, this week only",
    description:
      "Wet saw with a decent blade. I am between jobs. Return it clean. Del Norte, Saturday pickup at the hardware parking lot.",
    city: "Del Norte",
    region: "CO",
    lat: 37.6792,
    lng: -106.3531,
    fulfillment: "public",
    nationalOk: false,
    condition: "Good",
    giverName: "Andre",
    estimatedLbs: 35,
    hoursAgo: 16,
  },
  {
    id: "antonito-firewood",
    kind: "give",
    category: "materials",
    title: "Seasoned split pine, a pickup load",
    description:
      "We overdid the woodpile. Load what you can carry. Not for sale, not for resale. South of Antonito, easy dirt drive.",
    city: "Antonito",
    region: "CO",
    lat: 37.0792,
    lng: -106.0086,
    fulfillment: "pickup",
    nationalOk: false,
    condition: "Good",
    giverName: "Floyd",
    estimatedLbs: 200,
    hoursAgo: 28,
  },
  {
    id: "salida-seeds",
    kind: "give",
    category: "plants",
    title: "Saved seed envelopes — beans and squash",
    description:
      "Last year’s garden in paper packets, labeled. I’ll cover the stamps. Or pick up in Salida if you are already in town.",
    city: "Salida",
    region: "CO",
    lat: 38.5347,
    lng: -105.9989,
    fulfillment: "ship_prepaid",
    nationalOk: true,
    condition: null,
    giverName: "June",
    estimatedLbs: 1,
    hoursAgo: 36,
  },
  {
    id: "denver-couch",
    kind: "give",
    category: "goods",
    title: "Gray sofa, no pets, no smoke",
    description:
      "Moving out of a RiNo walk-up. Sofa is six years old, still square. You haul it down two flights. Weekend window.",
    city: "Denver",
    region: "CO",
    lat: 39.758,
    lng: -104.978,
    fulfillment: "pickup",
    nationalOk: false,
    condition: "Good",
    giverName: "Nate",
    estimatedLbs: 120,
    hoursAgo: 7,
  },
  {
    id: "boulder-sourdough",
    kind: "give",
    category: "food",
    title: "Sourdough starter, named Fern",
    description:
      "A cup of starter in a jar, fed this morning. Comes with a one-page note. Porch in north Boulder. Fern has opinions.",
    city: "Boulder",
    region: "CO",
    lat: 40.03,
    lng: -105.27,
    fulfillment: "porch",
    nationalOk: false,
    condition: null,
    giverName: "Claire",
    estimatedLbs: 1,
    hoursAgo: 11,
  },
  {
    id: "springs-ikea-help",
    kind: "offer",
    category: "help",
    title: "I will assemble one IKEA thing",
    description:
      "Allen keys and patience. Colorado Springs, one piece of furniture, one evening. I am not a contractor. I am a neighbor who has done this too many times.",
    city: "Colorado Springs",
    region: "CO",
    lat: 38.8339,
    lng: -104.8214,
    fulfillment: "pickup",
    nationalOk: false,
    condition: null,
    giverName: "Owen",
    estimatedLbs: 0,
    hoursAgo: 19,
  },
  {
    id: "pueblo-high-chair",
    kind: "give",
    category: "kids",
    title: "Wooden high chair",
    description:
      "Wiped down, straps intact. Our kid eats at the table now. Not a car seat, not recalled. Pueblo west side.",
    city: "Pueblo",
    region: "CO",
    lat: 38.2544,
    lng: -104.6091,
    fulfillment: "porch",
    nationalOk: false,
    condition: "Good",
    giverName: "Marisol",
    estimatedLbs: 18,
    hoursAgo: 25,
  },
  {
    id: "santa-fe-yarn",
    kind: "give",
    category: "goods",
    title: "Leftover wool, mostly earth tones",
    description:
      "A grocery bag of partial skeins from a sweater that ended. Happy to ship if you cover postage. Or collect in Santa Fe.",
    city: "Santa Fe",
    region: "NM",
    lat: 35.687,
    lng: -105.9378,
    fulfillment: "ship",
    nationalOk: true,
    condition: "Good",
    giverName: "Ida",
    estimatedLbs: 3,
    hoursAgo: 44,
  },
  {
    id: "abq-tutoring",
    kind: "offer",
    category: "help",
    title: "High-school algebra, remotely",
    description:
      "Retired teacher. One hour a week for a month, video. I have a whiteboard. No curriculum to sell.",
    city: "Albuquerque",
    region: "NM",
    lat: 35.0844,
    lng: -106.6504,
    fulfillment: "remote",
    nationalOk: true,
    condition: null,
    giverName: "Harold",
    estimatedLbs: 0,
    hoursAgo: 33,
  },
  {
    id: "durango-cooler",
    kind: "lend",
    category: "goods",
    title: "Large cooler for a river weekend",
    description:
      "70-quart, holds a block of ice. Back by Tuesday, rinsed. Durango. First person who can actually return it.",
    city: "Durango",
    region: "CO",
    lat: 37.2753,
    lng: -107.8801,
    fulfillment: "public",
    nationalOk: false,
    condition: "Good",
    giverName: "Sam",
    estimatedLbs: 15,
    hoursAgo: 10,
  },
  {
    id: "public-domain-patterns",
    kind: "give",
    category: "digital",
    title: "A folder of public-domain sewing patterns",
    description:
      "Scanned from old manuals, cleaned up, PDFs. I will email the link. Free as in actually free. US only because that is as far as Manna goes.",
    city: "Denver",
    region: "CO",
    lat: 39.7392,
    lng: -104.9903,
    fulfillment: "remote",
    nationalOk: true,
    condition: null,
    giverName: "Lin",
    estimatedLbs: 0,
    hoursAgo: 50,
  },
  {
    id: "portland-rain-jacket",
    kind: "give",
    category: "goods",
    title: "Rain jacket, men's medium",
    description:
      "A little scuffed at the cuffs, still waterproof. I can ship if you cover postage, or porch in Alberta Arts.",
    city: "Portland",
    region: "OR",
    lat: 45.5152,
    lng: -122.6784,
    fulfillment: "ship",
    nationalOk: true,
    condition: "Good",
    giverName: "Theo",
    estimatedLbs: 2,
    hoursAgo: 15,
  },
  {
    id: "chicago-ask-desk",
    kind: "ask",
    category: "goods",
    title: "Need a small desk, Logan Square",
    description:
      "Working from a kitchen table and losing the argument. Something that holds a laptop. I can pick up with a hatchback this weekend.",
    city: "Chicago",
    region: "IL",
    lat: 41.8781,
    lng: -87.6298,
    fulfillment: "pickup",
    nationalOk: false,
    condition: null,
    giverName: "Ren",
    estimatedLbs: 0,
    hoursAgo: 27,
  },
  {
    id: "austin-produce-box",
    kind: "give",
    category: "food",
    title: "CSA box we cannot finish",
    description:
      "Out of town Thursday. Unopened greens, carrots, a melon. East Austin porch, first come, please actually eat it.",
    city: "Austin",
    region: "TX",
    lat: 30.2672,
    lng: -97.7431,
    fulfillment: "porch",
    nationalOk: false,
    condition: null,
    giverName: "Maya",
    estimatedLbs: 10,
    hoursAgo: 4,
  },
  {
    id: "seattle-ladder",
    kind: "lend",
    category: "goods",
    title: "Extension ladder, one afternoon",
    description:
      "Twenty-four foot. I am not climbing for you, but you may borrow it. Ballard. A six-pack is not required and not requested.",
    city: "Seattle",
    region: "WA",
    lat: 47.6062,
    lng: -122.3321,
    fulfillment: "pickup",
    nationalOk: false,
    condition: "Good",
    giverName: "Erik",
    estimatedLbs: 40,
    hoursAgo: 21,
  },
  {
    id: "boston-template-resume",
    kind: "give",
    category: "digital",
    title: "Plain resume template, no account required",
    description:
      "A Google-doc-style outline I use with students. I will send a copy. No funnel, no newsletter.",
    city: "Boston",
    region: "MA",
    lat: 42.3601,
    lng: -71.0589,
    fulfillment: "remote",
    nationalOk: true,
    condition: null,
    giverName: "Francis",
    estimatedLbs: 0,
    hoursAgo: 60,
  },
  {
    id: "foothills-guitar-lesson",
    kind: "offer",
    category: "help",
    title: "One free guitar lesson, beginner",
    description:
      "Couch and a borrowed instrument, or video if you have your own. Fort Collins. I am not famous. I am slow and kind.",
    city: "Fort Collins",
    region: "CO",
    lat: 40.5853,
    lng: -105.0844,
    fulfillment: "remote",
    nationalOk: true,
    condition: null,
    giverName: "Leah",
    estimatedLbs: 0,
    hoursAgo: 13,
  },
  {
    id: "taos-blankets",
    kind: "give",
    category: "goods",
    title: "Two wool blankets",
    description:
      "Camp-grade, a little rustic, very warm. I can meet in the plaza lot. Not heirlooms — just extra warmth.",
    city: "Taos",
    region: "NM",
    lat: 36.4072,
    lng: -105.5731,
    fulfillment: "public",
    nationalOk: false,
    condition: "Fair",
    giverName: "Noel",
    estimatedLbs: 8,
    hoursAgo: 17,
    pickupPlace: "Plaza parking lot",
  },
  {
    id: "used-crib-alamosa",
    kind: "give",
    category: "kids",
    title: "Sturdy crib, current safety standard",
    description:
      "Outgrown in a season. Hardware complete, no drop-side. You will want a truck or a van. Porch on First Street through the weekend.",
    city: "Alamosa",
    region: "CO",
    lat: 37.471,
    lng: -105.863,
    fulfillment: "porch",
    nationalOk: false,
    condition: "Good",
    giverName: "Kate",
    estimatedLbs: 40,
    hoursAgo: 5,
    pickupPlace: "Porch on First Street",
  },
  {
    id: "campus-bike-give",
    kind: "give",
    category: "goods",
    title: "Mountain bike that still rolls",
    description:
      "Gears skip in the highest one. Brakes work. A student could get to class on it tomorrow. Lean it from the rack by the library if you cannot come to the house.",
    city: "Alamosa",
    region: "CO",
    lat: 37.4722,
    lng: -105.878,
    fulfillment: "pickup",
    nationalOk: false,
    condition: "Fair",
    giverName: "Wes",
    estimatedLbs: 28,
    hoursAgo: 8,
  },
  {
    id: "desk-logan-give",
    kind: "give",
    category: "goods",
    title: "Small oak desk, Logan Square",
    description:
      "Fits a laptop and a lamp. One drawer sticks. Third-floor walk-up; you carry it down. This weekend only.",
    city: "Chicago",
    region: "IL",
    lat: 41.923,
    lng: -87.709,
    fulfillment: "pickup",
    nationalOk: false,
    condition: "Good",
    giverName: "Quinn",
    estimatedLbs: 45,
    hoursAgo: 9,
  },
];
